//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 02:14:15 PM IST 
//


package com.jeet.api;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="seatNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="seatDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "seatNum",
    "seatDesc"
})
@XmlRootElement(name = "seat")
@Entity
public class Seat {
	@Id
    @XmlElement(required = true)
    protected String seatNum;
    @XmlElement(required = true)
    protected String seatDesc;

    /**
     * Gets the value of the seatNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeatNum() {
        return seatNum;
    }

    /**
     * Sets the value of the seatNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeatNum(String value) {
        this.seatNum = value;
    }

    /**
     * Gets the value of the seatDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeatDesc() {
        return seatDesc;
    }

    /**
     * Sets the value of the seatDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeatDesc(String value) {
        this.seatDesc = value;
    }

}
