 insert into movie values (1001, 'Romantic', 'DDLJ');
 insert into movie values (1002, 'Romantic', 'KKHH');
 insert into movie values (1003, 'Comedy', 'Dil');
 insert into screen values ('T1', 30, 1001);
 insert into screen values ('T2', 30, 1002);
 insert into screen values ('T3', 35, 1003);
 insert into seat values ('A1', 'corner');
 insert into seat values ('A2', 'corner');
 insert into seat values ('A3', 'corner');
 insert into seat values ('B1', 'corner');
 insert into seat values ('B2', 'corner');
 insert into seat values ('C1', 'corner');
 insert into seat values ('C2', 'corner');
 insert into screen_seat values ('T1','A1');
 insert into screen_seat values ('T1','A2');
 insert into screen_seat values ('T1','A3');
 insert into screen_seat values ('T1','B1');
 insert into screen_seat values ('T1','B2');
 insert into screen_seat values ('T1','C1');
 insert into screen_seat values ('T1','C2');
 insert into screen_seat values ('T2','A1');
 insert into screen_seat values ('T2','A2');
 insert into screen_seat values ('T2','A3');
 insert into screen_seat values ('T2','B1');
 insert into screen_seat values ('T2','B2');
 insert into screen_seat values ('T2','C1');
 insert into screen_seat values ('T2','C2');
 insert into screen_seat values ('T3','A1');
 insert into screen_seat values ('T3','A2');
 insert into screen_seat values ('T3','A3');
 insert into screen_seat values ('T3','B1');
 insert into screen_seat values ('T3','B2');
 insert into screen_seat values ('T3','C1');
 insert into screen_seat values ('T3','C2');